[project]
name = "pandas-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=33.3.1",
    "ipykernel>=6.29.5",
    "jupyterlab>=4.3.4",
    "notebook>=7.3.2",
    "pandas>=2.2.3",
]
